# Товары
## Получить список товаров
GET http://localhost:4000/products?page=1&type=Электрогитара&type=Акустическая гитара&stringsCount=7&stringsCount=6 HTTP/1.1
Content-Type: application/json

###

## Получить кол-во товаров
GET http://localhost:4000/products/pageCount HTTP/1.1
Content-Type: application/json

###

## Получить товар по Id
GET http://localhost:4000/products/65116dacfb05ec769a978e41 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY1MTA1OTdiYWRlOTk0MjY0MjM5ZjBmMCIsImlhdCI6MTY5NTcyMDE4OSwiZXhwIjoxNjk2MTUyMTg5fQ.YP_o_Qs9YbGETyvC5LIFIOpJjAwXdu58JcmF_l06WZI

###

## Добавить товар
POST http://localhost:4000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY1MTA1OTdiYWRlOTk0MjY0MjM5ZjBmMCIsImlhdCI6MTY5NTcyMDE4OSwiZXhwIjoxNjk2MTUyMTg5fQ.YP_o_Qs9YbGETyvC5LIFIOpJjAwXdu58JcmF_l06WZI

{
  "title": "Гитара хорошая 14",
  "description": "Описание 10 хорошая10 тест токена 2",
  "type": "акустика",
  "code": "123456789",
  "stringsCount": 4,
  "price": 1001
}

###

## Изменить товар
PATCH http://localhost:4000/products/65105d25ade994264239f0f8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY1MTA1OTdiYWRlOTk0MjY0MjM5ZjBmMCIsImlhdCI6MTY5NTcyMDE4OSwiZXhwIjoxNjk2MTUyMTg5fQ.YP_o_Qs9YbGETyvC5LIFIOpJjAwXdu58JcmF_l06WZI

{
  "price": 100
}

###

## Удалить товар
DELETE  http://localhost:4000/products/65105d25ade994264239f0f8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY1MTA1OTdiYWRlOTk0MjY0MjM5ZjBmMCIsImlhdCI6MTY5NTcyMDE4OSwiZXhwIjoxNjk2MTUyMTg5fQ.YP_o_Qs9YbGETyvC5LIFIOpJjAwXdu58JcmF_l06WZI

###

## Получить список товаров с фильтром по типу
GET http://localhost:4000/products/type?limit=10&type=Электрогитара&type=Акустическая гитара&stringsCount=7&stringsCount=6 HTTP/1.1
Content-Type: application/json

###

## Получить список товаров с фильтром по кол-ву струн
GET http://localhost:4000/products/strings?limit=10&stringsCount=4&stringsCount=12 HTTP/1.1
Content-Type: application/json

###

## Получить список товаров с сортировкой по цене
GET http://localhost:4000/products/sort?limit=30&sortType=1 HTTP/1.1
Content-Type: application/json

###

## Отправить изображение

POST http://localhost:4000/products/65152ce94d0a92d0e0df30d7/image HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY1MTA1OTdiYWRlOTk0MjY0MjM5ZjBmMCIsImlhdCI6MTY5NTcyMDE4OSwiZXhwIjoxNjk2MTUyMTg5fQ.YP_o_Qs9YbGETyvC5LIFIOpJjAwXdu58JcmF_l06WZI

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="productImage"; filename="add-item-1.png"
Content-Type: image/png

< D:/Projects/guitar-shop/frontend/markup/img/content/add-item-1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
